### ISSUE TITLE
ModuleNotFoundError: No module named 'kasserver'

### ISSUE THREAD

**Issue by Schwenniii** [fetzerch/kasserver#14]
Python version 3.12

if i run i get this error

installed with pipx and venv with the same result

ModuleNotFoundError: No module named 'kasserver'

**Comment by fetzerch** [comment]
Works for me. Please document the exact steps to reproduce the issue.

**Comment by Schwenniii** [comment]
solved the problem: deleting the kasserver files under usr/local/bin
