### ISSUE TITLE
Syntax Error after updating to the latest version

### ISSUE THREAD

**Issue by MinehubDE** [fetzerch/kasserver#8]
OS: Debian 9
Python Version: 3.5.3
Pip Version: pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)

Due to the change of the Kasserver API from SHA1 to PLAIN auth, we installed the latest kasserver package using pip.
That results in an Syntax error.
Its an old system and therefore not able to run Python 3.11.

kasserver-dns list example.com
Traceback (most recent call last):
  File "/usr/local/bin/kasserver-dns", line 7, in <module>
    from kasserver.kasserver_dns import cli
  File "/usr/local/lib/python3.5/dist-packages/kasserver/kasserver_dns.py", line 64
    f"{item['id']:>8} {item['changeable']:1} {item['zone']:20} "

Any ideas on how to fix this? Code changes to "bypass" the syntax error would also be enough, as we want to upgrade this server anyways. We just wont make it until our wildcard domains need their next certs.

**Comment by fetzerch** [comment]
I pushed a Python 3.5 compatible version to the python3.5 branch. It was pretty much just a revert of a single commit  that introduced f-strings in a few places.

```console
PBR_VERSION=0.3.0-python3.5 pip install https://github.com/fetzerch/kasserver/archive/refs/heads/python3.5.zip
```

**Comment by MinehubDE** [comment]
You're a god! Thank you very much, it worked.
